### ISSUE TITLE
Timestamp on Find Answers articles

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#2]
Timestamp is incorrect - the date is shown to be 1 day off compared to the ASPX version of some articles, but this seems to be only on some articles. Other are off by a small number of minutes.

**Comment by sdubrick** [comment]
Seems to be an issue in the base generic form as well

**Comment by sdubrick** [comment]
Example:
https://qa.iservicecrm.com/FindAnswers.aspx?topicID=1&articleID=1392
vs
https://qa.iservicecrm.com/f/87#/find-answers?topicID=1&articleID=1392

or see screenshot below.
I'm guessing the angular version shows the creation time instead of the last updated time.

![image](https://cloud.githubusercontent.com/assets/5289502/13071308/29fa0474-d4c5-11e5-8e1a-a5fef260205e.png)

**Comment by sdubrick** [comment]
#112

**Comment by sdubrick** [comment]
@scottwhitsitt i believe adam checked in a fix for this

**Comment by scottwhitsitt** [comment]
Verified the dates match on findanswer.aspx and the current built in form Version: 7.5 - 2016.07.24 - 17:13:22
