### ISSUE TITLE
List of topics not complete

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#6]
Logged in as an agent, I should have seen the private topics. Instead, I only see the public topics after login. Also, after sitting idle for about 2 minutes I reloaded the tab in FireFox. It seems to quickly reload (or might have reloaded in the background) and showed NO topics. Even clicking within the page did not bring the topics back.

I logged out and back in, and the inaccurate topic tree was still shown.

![temp](https://cloud.githubusercontent.com/assets/16782471/12539009/6ce7102a-c2ae-11e5-8cb8-75f52c2557e0.png)

The sub topics should be indented to the right. In the example below, there is no way to see the hierarchy. Some icon needs to be used to show the tree structure.

![temp](https://cloud.githubusercontent.com/assets/16782471/12539040/3b82cd70-c2af-11e5-9a26-19a32cc7871b.png)

**Comment by sdubrick** [comment]
Possibly a bug in how segment data is retrieved - talk to adam.

**Comment by sdubrick** [comment]
The problem is that the topic list only seems to show a single segment when an agent has access to multiple segments.  In the top screenshot above, when scott is logged in, it only shows the list of topics in segment QA2, but does not show the topics in segment QA. It should show all.

The original generic form does not have this issue, (see screenshot below) so it appears to be in the new code
![image](https://cloud.githubusercontent.com/assets/5289502/12593181/5a72ff02-c435-11e5-9519-4548289aa58f.png)

**Comment by sdubrick** [comment]
JC most likely did not see this bug because he only had access to segment QA.  (see below) i have added him to segment QA2 so that he can repro and fix it
![image](https://cloud.githubusercontent.com/assets/5289502/12593247/b24e8b56-c435-11e5-9815-fc05934695ee.png)
