### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by scottwhitsitt** [OneToOneService/iService-Forms#63]
The password reset link is not working

**Comment by ashrafsabrym** [comment]
I added the feature as implemented in ngappbuiltin-findanswers-sample:

``` javascript
var protocol = window.location.protocol,
            host = window.location.host,
            pathname = window.location.pathname,
            dirname = pathname.substring(0, pathname.lastIndexOf('/') + 1),
            resetUrl = protocol + '//' + host + dirname + rootPath + 'PasswordReset.aspx?confirm=$value -passwordreset(guid)$';

        $scope.errors = [];

        $scope.loading = iservice.PasswordResetSend($http, $scope.emailAddress, resetUrl, function (data)
        {
            $scope.errors = data.errors;

            if(data.errors && data.errors.length)
                return;

            $scope.forgot = false;
            $scope.sent = true;

        });
```

When I use it on my email, sometimes an error saying that password resetting is currently disabled for this account, and other times it sends this invalid password reset link: `https://qa.iservicecrm.com/PasswordReset.aspx?confirm=`. Seems that the `$value -passwordreset(guid)$` directive doesn't work for me.

**Comment by sdubrick** [comment]
It's happening because the value is being rendered on initial page load.  To stop that from happening change this line:
https://github.com/ashrafsabrym/iService-Forms/blob/6e94026aeabab8381252faacc52ab9e5fa9b3fa4/Assigned-Messages/MainBody.frm#L199

to:
`resetUrl = protocol + '//' + host + dirname + rootPath + 'PasswordReset.aspx?confirm=$' + 'value -passwordreset(guid)$';`

**Comment by ashrafsabrym** [comment]
I corrected it. Try it now.
